### ISSUE TITLE
0.2.0 still has ghost phrases

### ISSUE THREAD

**Issue by BHydden** [soupslurpr/Transcribro#22]
I am on 0.2.0 and just experienced an unspoken " Bye."  being added to the end of a recording.

**Comment by soupslurpr** [comment]
0.2.0 only manually removed a very common one which was " .". Unfortunately, " Bye." could actually be transcribed so the same thing can't be done. In the future when whisper.cpp can be ran with beam search quicker than how it is now, Transcribro would be able to use that which should reduce hallucinations. Bigger models can also reduce hallucinations.

**Comment by soupslurpr** [comment]
0.2.1 might reduce these more
