### ISSUE TITLE
Feature: enter key.

### ISSUE THREAD

**Issue by Charles7z** [soupslurpr/Transcribro#4]
The app works pretty good. The only thing missing on the keyboard is a return key so that you can allow the transcription to take place. Add a new paragraph and start another transcription without leaving the app, because you really can't just let the app run continuously, it'll choke sooner or later.

**Comment by soupslurpr** [comment]
I'm not sure what you mean by "a return key so that you can allow the transcription to take place". If you want to stop recognizing and transcribe immediately, please press the mic toggle button. Also can you elaborate on "you really can't just let the app run continuously, it'll choke sooner or later."

**Comment by Charles7z** [comment]
By return key, I mean an enter key to give you a new line or new paragraph.

 This is especially helpful when you're doing things like list items.

I originally did not realize that you could talk and then just pause for a few seconds to allow transcription to take place and then continue talking for more transcription. However if you talk too fast for too long you will get a mess of a transcription.  And it will all be one big paragraph.  The user needs to pause their speech or tap the mic to get transcription to take place Otherwise if they continue to talk It will not transcribe it will wait till the user pauses long enough Which can go on for a very long time and then the app develops problems with that much transcoding Thank you. Like it just did with that last sentence which should not be one sentence. The app works best when you give it a pause. Then continue your dictation. then give it another pause. and during these pauses you could use the Enter key for a new paragraph if you needed such things.

Essentially the feature request is to have a returned key so that you can enter a new paragraph and continued dictation without leaving the app and returning to the keyboard. 

I can somewhat do this now with the app if I enter a lot of returns before starting the app and just tap to a lower empty  line. It's just a very handy feature to have.

Right now I can use Sayboard with its edible keyboard to enter new lines and punctuation. However, your app doesn't need the punctuation or numbers. It just needs a new line key. I hope I've explained this properly.

And yes, this comment was done mostly with your app and a little bit with Sayboard. .😊

**Comment by soupslurpr** [comment]
Ah okay so you're suggesting an enter key for making new lines, that makes sense. Transcription quality will get better with the next release as it will use a bigger model which has better quality. You can try out a work in progress version of 0.2.0 in the below link if you want to see the improvement. Also fixes the " ." hallucination that sometimes happens :D

https://wormhole.app/Z9rX6#pAxynAplyqOtCpw742pjAA

**Comment by Charles7z** [comment]
The new version seems better, especially for punctuation. However, You have to pause a very long time before it will spit anything out. which means you can end up with a bit of a backlog You waiting for it to be spit out. However, from what I've noticed, It'll spit it out correctly with the right punctuation attached to the previous words in the proper sentence structure.

 As it just did above with only one oddball word, which could have been me.

**Comment by Charles7z** [comment]
I noticed something odd with the new version. At times when you're talking for a long time and you pause to let it catch up, it'll stick a word or two between the sentences. Often it's the phrase thank you or the word all. I cannot reproduce this consistently so I thought I would just share it with you to be on the Lookout. part. Thanks for watching.
 
 Well, it just did it in that last paragraph right at the end. Part, thanks for watching. Wasn't something I said.

**Comment by soupslurpr** [comment]
Unfortunately its an issue with the Whisper models hallucinating. Using bigger models helps a bit with it, but going above base would probably be too slow, but it is better than the tiny model at least.

**Comment by soupslurpr** [comment]
Future versions of whisper.CPP which is the library Transcribro uses to run the Whisper speech recognition model may improve this though.

> The new version seems better, especially for punctuation. However, You have to pause a very long time before it will spit anything out. which means you can end up with a bit of a backlog You waiting for it to be spit out. However, from what I've noticed, It'll spit it out correctly with the right punctuation attached to the previous words in the proper sentence structure.

> As it just did above with only one oddball word, which could have been me.

It's set to transcribe after 3 seconds of silence. This is so that punctuation stays. If it transcribed quicker, it may transcribe while doing a short pause and put a period instead of a comma.

**Comment by soupslurpr** [comment]
moved to #11
