### ISSUE TITLE
Sound when starting keyboard is annoying

### ISSUE THREAD

**Issue by tashijayla** [soupslurpr/Transcribro#50]
It would be great if there was an option to disable or control the volume of the voice recognition service startup sound. 

it would be great if their was a list of different sounds available for users to select from. This way, they could choose the sound that they think sounds the best.

Thank you for creating such an amazing app❤️. And being one of the first apps on Accrescent🎊🎉

**Comment by soupslurpr** [comment]
Well right now whether the audio feedback plays is dependent on what the ringer is set to. If you set it to sound, then the audio feedback plays. The volume of the audio feedback is dependent on your media volume.

**Comment by tashijayla** [comment]
If I use FUTO voice input, the sound it makes before it starts recording is at the perfect volume. Whether my phone's volume is set to loud or quiet, it always sounds good.

I think the sound it makes is better!, in my opinion.

It would be great if this app could use the same sound that FUTO Voice input makes.

I like to have my media volume set to loud almost all the time.

Unfortunately, I cannot switch from FUTO Voice Input to this app until the sound is less loud, even if my media volume is loud, because the sound it makes hurts my ears.

I've said my opinion. Thank you for your fast response, and I'm more than happy to close this issue if you like!

**Comment by soupslurpr** [comment]
For copyright reasons Transcribro can't use the same audio as FUTO Voice Input for the audio feedback, but a setting to enable, disable, or only play when ringer is set to sound would be fine. The default would remain only playing it when the ringer is set to sound. An option to control the sound would also be good.

**Comment by soupslurpr** [comment]
I just opened #51 and #52 to address this. Thanks for the feedback!
