### ISSUE TITLE
can't use the app on a Samsung device

### ISSUE THREAD

**Issue by 5wHN28Dg** [soupslurpr/Transcribro#55]
Samsung Galaxy Note 9 running A14 (OneUI 6.1) and I can't select the app as a voice input, it is not on the list, only Samsung and google voice input are available to select

![Screenshot_20240730_080613_Samsung Keyboard](https://github.com/user-attachments/assets/c65ace4b-e955-40df-9d0a-015d7bf8ec70)

**Comment by soupslurpr** [comment]
Do other speech recognition apps show up there? Does it show up if you turn off Arabic?

**Comment by 5wHN28Dg** [comment]
Okay so apparently I had to set the voice input to none and now the keyboard switching button is visible again and I can select transcribo

Well that's unfortunate because the on device arabic T2S from Samsung is really good, well that's something they need to fix, if I enable voice input, the keyboard switcher button gets replaced by the voice input button

![Screenshot_20240730_082150_One UI Home](https://github.com/user-attachments/assets/dd2cf33d-2b3f-4ffe-99e3-209fd0990812)
![Screenshot_20240730_082254_Firefox](https://github.com/user-attachments/assets/e1583a92-280f-4fdf-b260-d8a3bc80e5a1)
![Screenshot_20240730_082339_Firefox](https://github.com/user-attachments/assets/08d85e97-e535-43ce-b2b1-98af87be6e48)

**Comment by soupslurpr** [comment]
Oh no I was just asking you to try to disable Arabic just in case that's related but it probably isn't needed? So is everything working fine right now?

**Comment by 5wHN28Dg** [comment]
Oh sorry forgot to mention that, yes I tried disabling Arabic and it unfortunately didn't fix it, anyway yes everything is working fine now, thanks!

**Comment by soupslurpr** [comment]
Ah I see that's weird on them that they replace the keyboard switcher? Maybe try pressing or holding the globe instead it might have the same function?

**Comment by 5wHN28Dg** [comment]
> Maybe try pressing or holding the globe instead it might have the same function?

Damn you are right
![Screenshot_20240730_091047_Firefox](https://github.com/user-attachments/assets/1de1042e-2b46-4c06-964a-e38929bf852e)

**Comment by soupslurpr** [comment]
Yayyy lol

**Comment by 5wHN28Dg** [comment]
And also I figured that these voice input settings are for samsung voice input not global settings for voice input so that's why disabling Arabic didn't do a thing because what it did is just disable Arabic for samsung voice input, when I select google voice input all of these options disappear and now I'm wondering why only samsung and google voice inputs are available, why Transcribe isn't there, is it hardcoded or something need to change in Transcribe for it to be an option🤔

Anyway I can use Transcribe now so yayyy

![Screenshot_20240730_080613_Samsung Keyboard](https://github.com/user-attachments/assets/058273f2-6f43-4ebc-a6e8-8a6c90c8572a)

**Comment by soupslurpr** [comment]
Yeah that's really weird, seems Samsung might not let you select others?

**Comment by soupslurpr** [comment]
I don't think its anything to do with Transcribro since it works fine on AOSP based OS' and it follows the Android docs on how to expose itself as a voice input service.
