### ISSUE TITLE
 Double period at the end of sentence.

### ISSUE THREAD

**Issue by Charles7z** [soupslurpr/Transcribro#8]
If you stop talking just long enough at the end of the sentence and then tap the microphone to end dictation, you'll end up with two periods at the end of the sentence. .

 just like what happened on that sentence above.

 It seems the app has already put in the period for when you pause your talking, but then you tap the microphone and it adds another period. This doesn't seem to happen all the time. .

 But I got it to happen twice in this comment. .

 Now three times. 😉

**Comment by soupslurpr** [comment]
Fixed while you were making this in https://github.com/soupslurpr/Transcribro/commit/8546b736fc6bcd85fa28a4d7120dd410a4af5e93, read the comment in the enter key feature issue 😆
