### ISSUE TITLE
Does not support Chinese character recognition. 不支持中文识别

### ISSUE THREAD

**Issue by Liu8Can** [soupslurpr/Transcribro#82]
Can't recognize chinese. Maybe only English. If Chinese recognition is considered, I will be extremely grateful.

**Comment by soupslurpr** [comment]
Yes, it's English-only for now. More languages are planned, but more work needs to be done before that such as refactors or rewrites, and switching to using Rust to run the models.

#27 is the issue for multiple languages support. As many languages as possible will be supported so there's no need to have language specific issues for now.
