### ISSUE TITLE
Transcriptions are extremely delayed

### ISSUE THREAD

**Issue by An-anonymous-coder** [soupslurpr/Transcribro#83]
While transcribing text, live transcriptions do not show up. Transcriptions only show up after the transcription is stopped. If "Auto-Stop Recognition" is enabled, it takes about 10 seconds to show up.

https://github.com/user-attachments/assets/defc930d-6e30-4f5c-aace-6b8a75173c50

**Device:** Google Pixel 8 (GKWS6)
**Android distribution:** GrapheneOS
**Build number:** 2024120900
**Android version:** Android 15 (AP4A.241205.013)
**Android security update:** December 5, 2024
**Installation method:** Accrescent
**App version:** version 0.3.0
**App version code:** versionCode 5

**Comment by soupslurpr** [comment]
It starts processing the transcription after 3 seconds of silence or when manually stopping it. Real-time transcription isn't supported.

**Comment by soupslurpr** [comment]
Maybe, but not sure. Whisper might not be able to do that efficiently. Whisper.cpp doesn't have such an option and there aren't any Rust runtimes for Whisper that are as fast as whisper.cpp yet.
